# Generated by Django 3.2.8 on 2022-04-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Өтініш күйі'),
        ),
    ]
