# Generated by Django 3.2.8 on 2022-04-20 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='rent',
        ),
        migrations.RemoveField(
            model_name='request',
            name='rent_count',
        ),
        migrations.AddField(
            model_name='order',
            name='rent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.rent', verbose_name='Төлем ақы түрі'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='rent_count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Төлем жиілігі'),
            preserve_default=False,
        ),
    ]
