# Generated by Django 3.2.8 on 2022-05-02 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0002_delete_organizationdormmanager'),
        ('order', '0005_request_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dorm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dorm.dorm', verbose_name='Жатақхана'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='rent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.rent', verbose_name='Төлем ақы түрі'),
        ),
        migrations.AlterField(
            model_name='order',
            name='rent_count',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Төлем жиілігі'),
        ),
    ]
