# Generated by Django 3.2.8 on 2022-05-02 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20220502_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='rent_count',
        ),
    ]
