# Generated by Django 3.2.8 on 2022-03-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Жатақхана',
                'verbose_name_plural': 'Жатақханалар',
                'db_table': 'dorm',
            },
        ),
    ]
