# Generated by Django 3.2.8 on 2022-04-09 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220409_0909'),
        ('dorm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationDormManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorm.organization', verbose_name='Ұйым')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='Жатақ басқарушы')),
            ],
            options={
                'verbose_name': 'Ұйымның жатақ басқарушысы',
                'verbose_name_plural': 'Ұйымның жатақ басқарушылары',
                'db_table': 'organization_dorm_manager',
            },
        ),
    ]
