# Generated by Django 3.2.8 on 2022-04-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Қала атуы'),
        ),
    ]
