# Generated by Django 3.2.8 on 2022-05-02 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizationDormManager',
        ),
    ]
