# Generated by Django 3.2.8 on 2022-04-09 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0002_organizationdormmanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationdormmanager',
            old_name='user',
            new_name='dorm_manager',
        ),
    ]
