# Generated by Django 3.2.8 on 2022-04-03 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_fullname'),
        ('dorm', '0002_alter_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorm',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='Құрушы'),
            preserve_default=False,
        ),
    ]
