# Generated by Django 3.2.8 on 2022-04-05 04:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_fullname'),
        ('dorm', '0003_dorm_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dorm',
            name='creator',
        ),
        migrations.AddField(
            model_name='dorm',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Құрылған уақыт'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Ұйым атуы')),
                ('category', models.CharField(choices=[('university', 'Университет'), ('college', 'Колледж'), ('school', 'Мектеп'), ('other', 'Басқа')], max_length=10, verbose_name='Санат')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Құрылған уақыт')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='Құрушы')),
            ],
            options={
                'verbose_name': 'Ұйым',
                'verbose_name_plural': 'Ұйымдар',
                'db_table': 'dorm_organization',
            },
        ),
        migrations.AddField(
            model_name='dorm',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dorm.organization', verbose_name='Ұйым'),
            preserve_default=False,
        ),
    ]
