# Generated by Django 3.2.8 on 2022-04-11 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0003_rename_user_organizationdormmanager_dorm_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormimage',
            name='dorm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dorms', to='dorm.dorm', verbose_name='Жатақхана'),
        ),
    ]
