# Generated by Django 3.2.8 on 2022-04-11 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0004_alter_dormimage_dorm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormimage',
            name='dorm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorm.dorm', verbose_name='Жатақхана'),
        ),
    ]
