# Generated by Django 3.2.8 on 2022-03-28 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Тіркелген уақыт'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(default='u_2022032817', max_length=50, verbose_name='Аты жөн'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('site admin', 'Сайт әкімшісі'), ('dorm manager', 'Жатақхана меңгеруші'), ('tenant', 'Жалға алушы')], max_length=25, verbose_name='Рөл'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=254, verbose_name='Мазмұны')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Жіберілген уақыт')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user', verbose_name='Жіберуші')),
            ],
            options={
                'verbose_name': 'Пайдаланушының кері байланысы',
                'verbose_name_plural': 'Пайдаланушылардың кері байланыстары',
                'db_table': 'user_feedback',
            },
        ),
    ]
