# Generated by Django 3.2.8 on 2022-04-07 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=254, verbose_name='Мазмұны')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Жіберілген уақыт')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='user.user', verbose_name='Алушы')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to='user.user', verbose_name='Жіберуші')),
            ],
            options={
                'verbose_name': 'Хабарландыру',
                'verbose_name_plural': 'Хабарландырулар',
                'db_table': 'notification',
            },
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
