# Generated by Django 3.2.8 on 2022-04-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(default='u_2022041417', max_length=50, verbose_name='Аты жөн'),
        ),
    ]
