# Generated by Django 3.2.8 on 2022-03-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220328_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(default='u_2022032922', max_length=50, verbose_name='Аты жөн'),
        ),
    ]
