# Generated by Django 3.2.8 on 2022-03-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.BooleanField(default=False, verbose_name='Жыныс'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(default='u_2022033010', max_length=50, verbose_name='Аты жөн'),
        ),
    ]
