# Generated by Django 3.2.8 on 2022-04-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220420_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(default='u_2022042022', max_length=50, verbose_name='Аты жөн'),
        ),
    ]
