# Generated by Django 3.2.8 on 2022-04-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220409_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(default='u_2022040917', max_length=50, verbose_name='Аты жөн'),
        ),
    ]
