# Generated by Django 3.2.8 on 2022-04-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(default='u_2022042110', max_length=50, verbose_name='Аты жөн'),
        ),
    ]
