# Generated by Django 3.2.8 on 2022-04-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(default='u_2022040510', max_length=50, verbose_name='Аты жөн'),
        ),
    ]
